// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJO1X-3lBsDaW9mPB1M5rxd920aCmxj50',
    appId: '1:490371470024:web:a18738bc3a2574b4480bfd',
    messagingSenderId: '490371470024',
    projectId: 'sms-buy-sell',
    authDomain: 'sms-buy-sell.firebaseapp.com',
    storageBucket: 'sms-buy-sell.appspot.com',
    measurementId: 'G-X6LXHSKR5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm5YE9uLNn-UHMulqwgUuzQH1IQHF07WY',
    appId: '1:490371470024:android:ff27d1943741d494480bfd',
    messagingSenderId: '490371470024',
    projectId: 'sms-buy-sell',
    storageBucket: 'sms-buy-sell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXksXPSzkXPu5BR4_N94xWVJ2SVZXLt3E',
    appId: '1:490371470024:ios:0b199b1ac1e2e008480bfd',
    messagingSenderId: '490371470024',
    projectId: 'sms-buy-sell',
    storageBucket: 'sms-buy-sell.appspot.com',
    androidClientId: '490371470024-q7b1ehlqej6cdt5728cevbakmjii67h2.apps.googleusercontent.com',
    iosClientId: '490371470024-ja5huv6qk2kok08ma21evadts0r65uns.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXksXPSzkXPu5BR4_N94xWVJ2SVZXLt3E',
    appId: '1:490371470024:ios:0b199b1ac1e2e008480bfd',
    messagingSenderId: '490371470024',
    projectId: 'sms-buy-sell',
    storageBucket: 'sms-buy-sell.appspot.com',
    androidClientId: '490371470024-q7b1ehlqej6cdt5728cevbakmjii67h2.apps.googleusercontent.com',
    iosClientId: '490371470024-ja5huv6qk2kok08ma21evadts0r65uns.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
